use wasm_bindgen::prelude::*;

use crate::compression::inflater::Inflater;

#[cfg(not(target_feature = "atomics"))]
#[global_allocator]
static TALC: talc::wasm::WasmDynamicTalc = talc::wasm::new_wasm_dynamic_allocator();

/// Decodes/Decompresses a Deflate stream.
///
/// This function supports:
///
/// - Stored blocks
/// - Fixed Huffman blocks
/// - Dynamic Huffman blocks
#[wasm_bindgen]
pub fn decompress(data: &[u8]) -> Result<Vec<u8>, JsError> {
    Inflater::new(data).inflate().map_err(|e| JsError::new(&e))
}

/// Decompressed output that stays in wasm memory, so JS can read it through a
/// `Uint8Array` view instead of copying it out. Freed by `free()` (generated by
/// wasm-bindgen), or by the garbage collector if JS forgets.
#[wasm_bindgen]
pub struct DecompressedBuffer {
    data: Vec<u8>,
}

#[wasm_bindgen]
impl DecompressedBuffer {
    /// Address of the first byte in wasm memory.
    #[wasm_bindgen(getter)]
    pub fn ptr(&self) -> *const u8 {
        self.data.as_ptr()
    }

    /// Number of bytes.
    #[wasm_bindgen(getter)]
    pub fn len(&self) -> usize {
        self.data.len()
    }
}

/// Like `decompress`, but keeps the output in wasm memory (see `DecompressedBuffer`).
#[wasm_bindgen(js_name = decompressToBuffer)]
pub fn decompress_to_buffer(data: &[u8]) -> Result<DecompressedBuffer, JsError> {
    let data = Inflater::new(data).inflate().map_err(|e| JsError::new(&e))?;
    Ok(DecompressedBuffer { data })
}
